### タスク一覧
GET http://localhost:8000/api/tasks

### タスク詳細
GET http://localhost:8000/api/tasks/1
### タスク作成
### タスク作成
POST http://localhost:8000/api/tasks
Content-Type: application/json

{
  "user_id": 1,
  "title": "買い物",
  "content": "牛乳を買う",
  "week_days": ["月","水","金"],
  "start_time": "09:00",
  "duration_hours": "0",
  "duration_minutes": "30",
  "priority": "中",
  "color": "#ff0000",
  "start_date": "20250605",
  "end_date": "20251231"
}
### スケジュール一覧
GET http://localhost:8000/api/schedules

### スケジュール登録
POST http://localhost:8000/api/schedules
Content-Type: application/json

{
    "task_id": 1,
    "user_id": 1,
    "scheduled_date": "2025-06-05"
}

### スケジュール詳細
GET http://localhost:8000/api/schedules/1

### スケジュール削除
DELETE http://localhost:8000/api/schedules/1


### グループ一覧
GET http://localhost:8000/api/groups

### グループ作成
POST http://localhost:8000/api/groups
Content-Type: application/json

{
  "name": "エンジニア",
  "icon": "muscle.png",
  "invite_code": "ABC124",
  "description": "筋トレ仲間募集",
  "is_public": 1
}

### グループ参加
POST http://localhost:8000/api/groups/join
Content-Type: application/json

{
  "group_id": 2,
  "user_id": 2
}
### グループ削除
DELETE http://localhost:8000/api/groups/1

### グループタスク一覧
GET http://localhost:8000/api/grouptasks

### グループタスク作成
POST http://localhost:8000/api/grouptasks
Content-Type: application/json

{
    "group_id": 2,
    "title": "発表資料作成",
    "content": "スライド10枚作る",
    "created_by": 1
}

### グループタスク削除
DELETE http://localhost:8000/api/grouptasks/2